In [143]:
# Generate a random vector with max values supplied by a type
import numpy as np

def generate_random_vector(max_values):
    return np.array([np.random.choice(dim,1)[:] for dim in max_values])[:,-1]

max_values = (4,4)
print(generate_random_vector(max_values))

[1 2]


In [67]:
# Introduce a token in an entry position (drop it in from the top in the case of 2D or 3D)
# Token should "slide" down first dimension (gravity) and settle
import numpy as np

game_board = np.zeros((4,3,3), dtype=np.int8)
#print(game_board)

def place_token(token_value, entry_vector):
    
    assert np.abs(token_value) == 1, "token can only have value 1 or -1"
    
    entry_vector_shape = len(game_board.shape)-1
    assert len(entry_vector) == entry_vector_shape, "entry vector must have length %d" % entry_vector_shape
    
    #print(entry_vector)
    
    print(game_board[:,0,0])
    
    token_fall_coordinate = np.sum(np.abs(game_board[:,entry_vector]))
    
    #print(token_fall_coordinate)
    
    token_final_location = np.concatenate((np.array([token_fall_coordinate], dtype=np.int64), entry_vector))
    
    game_board[np.expand_dims(token_final_location,1).tolist()] = token_value
    return game_board

entry_vector = [0,0]
game_board = place_token(1, entry_vector)

entry_vector = [0,0]
game_board = place_token(-1, entry_vector)
#print(game_board)



[0 0 0 0]
[1 0 0 0]


In [78]:
# Find all the vectors we need to check along in K dimensions to see if there are N tokens in a row
import numpy as np

# 3 dimensions
#
# Straight
# 1,0,0
# 0,1,0
# 0,0,1
#
# Diagonals
#  1, 1, 0
#  1,-1, 0
#  1, 0, 1
#  1, 0,-1
#  0, 1, 1
#  0, 1,-1
#
#  1, 1, 1
#  1,-1, 1
# -1,-1, 1
# -1, 1, 1
#
 
# Pattern is similar to base 3
#  0  0  1
#  0  0 -1 - == -x[1]
#  0  1  0
#  0  1  1
#  0  1 -1
#  0 -1  0 - == -x[3]
#  0 -1  1 - == -x[5]
#  0 -1 -1 - == -x[4]
#  1  0  0
#  1  0  1
#  1  0 -1 
#  1  1  0
#  1  1  1
#  1  1 -1
#  1 -1  0 
#  1 -1  1 
#  1 -1 -1
# -1  0  0 - == -x[9]
# -1  0  1 - == -x[11]
# -1  0 -1 - == -x[10]
# -1  1  0 - == -x[15]
# -1  1  1 - == -x[17]
# -1  1 -1 - == -x[16]
# -1 -1  0 - == -x[12]
# -1 -1  1 - == -x[14]
# -1 -1 -1 - == -x[13]

def convert_to_vector(value, K):
    #print("value to convert %d" % value)
    vector = np.zeros(K)
    for k in range(0, K):

        base3_power = 3**((K-1)-k)

        a = int(value / base3_power)
        value = value % base3_power

        
        vector[k] = a if a<2 else -1
        
    return vector
        
vectors = []
K = 3
for i in range(0, K):
    
    take = 3**i
    print("Take %d" % take)
    for j in range(0, take):
        converted_vector = convert_to_vector(take + j, K)
        print("converted vector %s" % converted_vector)
        vectors.append(converted_vector)


Take 1
converted vector [ 0.  0.  1.]
Take 3
converted vector [ 0.  1.  0.]
converted vector [ 0.  1.  1.]
converted vector [ 0.  1. -1.]
Take 9
converted vector [ 1.  0.  0.]
converted vector [ 1.  0.  1.]
converted vector [ 1.  0. -1.]
converted vector [ 1.  1.  0.]
converted vector [ 1.  1.  1.]
converted vector [ 1.  1. -1.]
converted vector [ 1. -1.  0.]
converted vector [ 1. -1.  1.]
converted vector [ 1. -1. -1.]


In [151]:
import numpy as np

np.zeros((6,7), dtype=np.uint8)[[1]]


array([[0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [148]:
import numpy as np
choose_position = np.array([0],dtype=np.int8)

game_board = np.zeros((4,6), dtype=np.int8)

game_board[0,0] = 1
game_board[1,0] = 1
game_board[2,0] = 1

print(game_board[:,0])


print(game_board[[slice(None)] + choose_position.tolist()])


[1 1 1 0]
[1 1 1 0]


array([0, 0, 0, 0], dtype=int8)

In [16]:
import numpy as np

a = np.zeros(16)
a[8] = 1
np.array(np.where(a.reshape([4,4])==1)).flatten()

array([2, 0])